language: bash

services: docker

env:
  global:
    - secure: "fNqh2CJxo1BxMcPtaMDsiQFYKw2bjstDTOAKhImRZKQ0egSP3gMlEep9YABKgYH6kyCnBOZbAZsz5nedzXkH1PCFIgNpZi/Cglfa70YVfEQaM9BDeEJ5tiv7BOWCDvRlPZ2l8gFkdnXeL/93JN9onHm5xfq3ea3NSrEtGE66io++OdWPzskjJxzkr78NWPAyjoIAe5ONrJdxzC5FIMZrgQQpHdpU7w8TyNs1LnvRFVz5cEyYNfZ0qrSewWv9ZX761UwBqRLOVW2yDaF5xc6LlHf0bN3GiBVwaJ4ISgr7iEL3HNIlXjckD1/wPALko0Tzn3aVpVUYchrqFs5cl8Vq3g9nZtih/xZU4wce0NfhBT864lfNS1z4wVGNM/b92IjmUvyU6X5RcfxSxvwV+uFFOqct12MzAPx/QUolcWeMvHMBrOm9qTZ2Vex2WV4zyls6aEtb7ONkiYd/jAdWov+3BYN+zQ8hO0ZcO2V1Z6Vf/0raWBKJRhMHbeL/0YLfjSyVJSniAcJzc2nZjxa+md0oiySdzkGfOTpDULQWGmOYniKVLeKJ7ZzuBH0NfyMkNfSlFcAMZDQlfDYVqL/wRUEpcpu75XTK10NzvZrEo7pN+lB71zPHyryl9VBSLiPGUpiyvADSWs3DICbpa/yifT7CKMnqWHYmHYWsHbra+XT4wKA="
    - secure: "lyRyBXYDxtR2f8ClZm8W9MJYOUUjAm4BaVqRmiIkB7fBL+bDSjKw+7khSPo1wtN4eqH0UXsXpZwMcDdv6vGgmh2HNiorP+RuTg9BaXRznSqrjPgiOyJgO3lBPNTGVBBwsugSsM5CK9HEZ4GpHWWawu6TXQbEmDB5e0EsN5RGZMVChaKCJ3a5veNty+62mPRrCIVJmWszWUN7ez8PzBbXzRlzqKAt2kPrqeoOqFyY4+64ltsuky3+IG3l3LYmUoYFj1Z7198WOOGZ80QYUGo+jTkaa+qC5HxpI6oLUYJ6/vM4RaCMkRZzixbARoyseIEPj+P5dC8UYJgsWBE+72/JiSD5nizto8aO3b9iSErxcCT/1RRuu3MRVdriDOlbGpqTXDE09VlBZrPBTAG7vdndeU40kUSAO0Ve6MeobkL485/SRus22vsHf5tLwudhCoiao+3c2vw6UXHWBfgb7tIHSp94fxFd+fLkjaCyLT3RlBnKcpP/5Nxnk7Hahjq/oIKgmm/hYQMd5Jas6lByMG1nFAk/XoKcvPlnsTcs2/Lk4CvUDCVRaJFzH8EgUuWtucx8vdoRQpp/WIUO912ntK9bG7mfuEVpQwDGinV3SGkvCO+uns+9eZjlXPyUdNp1ItxJFfGtJhAuTq86hokTZ5lJfUB8EJaiMTE4oJYPwu6Aspw="
  matrix:
    - VERSION=latest

before_script:
  - cd src/
  - IMAGE_NAME="chesszebra/$(echo "$TRAVIS_REPO_SLUG" | cut -c 25-):${VERSION}"

script:
  - docker build -t "$IMAGE_NAME" .

after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push $IMAGE_NAME

after_script:
  - docker images

notifications:
  email: false
